bozorlik = ['Gosht', 'Tuxum', 'Kartoshka', 'Un', 'Yog', 'Piyoz']
print(bozorlik)
olindi = []
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
xarid = input('nima xarid qilamiz').capitalize()
bozorlik.remove(xarid)
olindi.append(xarid)
print(bozorlik)
print(olindi)
